### ISSUE TITLE
tcmalloc/jemalloc reversed in docs

### ISSUE THREAD

**Issue by mattspatola** [yakushstanislav/EagleMQ#13]
To compile against tcmalloc, use:

```
% make MALLOC=jemalloc
```

To compile against jemalloc, use:

```
% make MALLOC=tcmalloc
```

Believe you want to reverse those two make lines or the captions above them.

**Comment by yakushstanislav** [comment]
Hello @mattspatola. Fixed in 31e1620c0a3cbbdb39675fc7432aac13686fe0b9.

Thank you.
